version: 1

loggers:
  revscoring:
    level: ERROR
    handlers: [stdout]
  ores:
    level: WARNING
    handlers: [stdout]
  celery:
    level: WARNING
    handlers: [file]

handlers:
  stdout:
    class: logging.StreamHandler
    formatter: basic_human
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    filename: /srv/ores/logs/main.log
    when: midnight
    backupCount: 7

formatters:
  basic_human: 
    format: "%(asctime)s %(levelname)s:%(name)s -- %(message)s"

